apiVersion: v1
kind: ServiceAccount
metadata:
  name: apibinder
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apibinder
rules:
  - apiGroups:
      - apis.kcp.io
    resources:
      - apibindings
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apibinder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apibinder
subjects:
  - kind: ServiceAccount
    name: apibinder
    namespace: default
