apiVersion: v1
current-context: root
kind: Config
preferences: {}
clusters:
- cluster:
    certificate-authority: /opt/homebrew/etc/pki/ca.crt
    server: https://127.0.0.1:6443
  name: base
- cluster:
    certificate-authority: /opt/homebrew/etc/pki/ca.crt
    server: https://127.0.0.1:6443/clusters/root
  name: root
- cluster:
    certificate-authority: /opt/homebrew/etc/pki/ca.crt
    server: https://127.0.0.1:6443/clusters/system:admin
  name: system:admin
users:
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://127.0.0.1:5556/dex
      - --oidc-client-id=kcp
      - --oidc-client-secret=kcp
      - --certificate-authority=/opt/homebrew/etc/pki/ca.crt
      command: kubectl
      env: null
      interactiveMode: Never
      provideClusterInfo: false
contexts:
- context:
    cluster: root
    user: oidc
  name: root
