---
apiVersion: apis.kcp.io/v1alpha1
kind: APIBinding
metadata:
  name: pki.massive.corp
spec:
  reference:
    export:
      name: pki.massive.corp
      path: "root:pki"
  permissionClaims:
  - resource: secrets
    state: Accepted
    all: true
