apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusters.url.test
spec:
  group: url.test
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
      subresources:
        status: {}
  scope: Cluster
  names:
    plural: clusters
    singular: cluster
    kind: Cluster
    listKind: ClusterList
