---
apiVersion: apis.kcp.io/v1alpha1
kind: APIResourceSchema
metadata:
  name: v1.certificates.pki.massive.corp
spec:
  scope: Namespaced
  group: pki.massive.corp
  names:
    kind: Certificate
    listKind: CertificateList
    plural: certificates
    singular: certificate
  versions:
  - name: v1alpha1
    schema:
      description: 'A certificate from the internal PKI.'
      type: object
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CertificateSpec holds the desired state of the Certificate.
          type: object
          properties:
            hostname:
              type: string
        status:
          description: CertificateStatus communicates the observed state of the Certificate.
          type: object
          properties:
            result:
              type: string
    served: true
    storage: true
    subresources:
      status: {}
