---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: kcp
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31443
        hostPort: 31443
        protocol: TCP
    labels:
      ingress-ready: true
