apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: massive-corp-ca-issuer
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: massive-corp-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: massive.corp
  secretName: massive-corp-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: massive-corp-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: massive-corp-ca
  namespace: cert-manager
spec:
  ca:
    secretName: massive-corp-ca
