---
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: certificate
spec:
  schema:
    apiVersion: v1alpha1
    kind: Certificate
    spec:
      hostname: string
      emails: string
    status:
      notAfter: ${cert.status.notAfter}
      notBefore: ${cert.status.notBefore}
      renewalTime: ${cert.status.renewalTime}
      revision: ${cert.status.revision}
  resources:
    - id: cert
      template:
        apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: ${schema.spec.hostname}
        spec:
          secretName: ${schema.spec.hostname}

          privateKey:
            algorithm: RSA
            encoding: PKCS1
            size: 2048

          usages:
            - server auth

          subject:
            organizations:
              - cert-manager

          commonName: ${schema.spec.hostname}.massive.corp

          dnsNames:
            - ${schema.spec.hostname}.massive.corp
          emailAddresses:
            - ${schema.spec.emails}

          issuerRef:
            name: massive-corp-ca
            kind: ClusterIssuer
            group: cert-manager.io
