---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-certificate
  namespace: test-certificate
spec:
  secretName: test-certificate

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  usages:
    - server auth

  subject:
    organizations:
      - cert-manager

  commonName: test.massive.corp

  dnsNames:
    - test.massive.corp
  emailAddresses:
    - example@massive.corp

  issuerRef:
    name: massive-corp-ca
    kind: ClusterIssuer
    group: cert-manager.io
