---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: custom:reader
rules:
- apiGroups: [""]
  resources:
    - secrets
    - configmaps
  verbs:
    - get
    - watch
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reader
subjects:
- kind: Group
  name: custom:reader
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: custom:reader
  apiGroup: rbac.authorization.k8s.io
