apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kcp:workspace:access
subjects:
- kind: Group
  name: custom:reader
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: system:kcp:workspace:access
  apiGroup: rbac.authorization.k8s.io
